### ISSUE TITLE
[Bug] JS error when adding Room actions

### ISSUE THREAD

**Issue by gr3ger** [FrankerFaceZ/FrankerFaceZ#1226]
**Describe the bug**
FFZ fails to add actions around the chat input.
Chat » Actions » Room

Affects both Opera GX, Firefox, and Chrome.

Error from console: 

```
logging.js:148 FFZ [site.chat.input]: TypeError: f.props.children.unshift is not a function
    at e.render (input.jsx:252:32)
    at qa (vendor-ebab964e6c486eed7aab.js:1:749951)
    at Ba (vendor-ebab964e6c486eed7aab.js:1:749746)
    at _s (vendor-ebab964e6c486eed7aab.js:1:785360)
    at gc (vendor-ebab964e6c486eed7aab.js:1:776801)
    at hc (vendor-ebab964e6c486eed7aab.js:1:776726)
    at ac (vendor-ebab964e6c486eed7aab.js:1:773756)
    at vendor-ebab964e6c486eed7aab.js:1:725397
    at t.unstable_runWithPriority (vendor-ebab964e6c486eed7aab.js:1:800673)
    at Ho (vendor-ebab964e6c486eed7aab.js:1:725106)
```

**Comment by gr3ger** [comment]
Closing since the issue seems to have been resolved
