### ISSUE TITLE
DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

### ISSUE THREAD

**Issue by DiFFoZ** [FrankerFaceZ/FrankerFaceZ#1491]
**Describe the bug**
No emotes shown typed by users, but if typing myself then it will show.

**To Reproduce**
1. Go to online stream.
2. See error on console.

**Expected behavior**
Emotes should show.

**Environment:**
 - OS: Linux mint
 - Browser Google Chrome 124
 - Other Extensions: Adblock

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://pastebin.com/kWVa7bbi

**Additional context**
Opening console, I see the error popup when someone typing emote name:
```
FFZ [site.chat.chat_line]: DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at RGBAColor.fromName (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:301:47608)
    at RGBAColor.fromCSS (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:301:47795)
    at Object.process (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:170:7503)
    at S._get (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:300:18361)
    at S.get (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:300:18970)
    at _.process (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:220:2888)
    at _.tokenizeMessage (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:171:17724)
    at x.ffzNewRender (https://cdn.frankerfacez.com/script/avalon.js?_=1713867996509:247:3159)
    at Es (https://static.twitchcdn.net/assets/vendor-c759dc8fc17d69cf50b2.js:1:1029939)
    at Ss (https://static.twitchcdn.net/assets/vendor-c759dc8fc17d69cf50b2.js:1:1029737)
```

**Comment by DiFFoZ** [comment]
After some debugging I found out it is because of my highlight settings color "rgba(0,0,0,0)". For some reason, FFZ doesn't allow me to set alpha to zero.
